site_name: Strata Documentation
site_description: "Strata - Collect. Plan. Grow."

repo_url: https://github.com/francoiducat/hugo-air
repo_name: francoiducat/hugo-air

theme:
  name: material
  palette:
    primary: teal
    accent: teal
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.tracking

  icon:
    repo: fontawesome/brands/github
    sets:
      - material
      - octicons

extra:
  copyright:
    text: "Strata - Collect. Track. Grow."

nav:
  - Strata App:
      - Overview: StrataApp.md
      - Features: Features.md
      - Use Cases: UseCases.md
  - Developer Docs:
      - Quick Start: QuickStart.md
      - Tech Stack: TechStack.md
      - Architecture: Architecture.md
      - Data Model: DataModel.md
      - Mental Model: MentalModel.md
      - Alembic: Alembic.md
      - Validation: Validation.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __code
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: <strong>Strata</strong> - Collect. Plan. Grow.
